/******************************************************************************
 * EslConfig.java
 * GENERATED BY StructCompiler, DON'T MODIFY MANULLY.
 * Generated Time: Sat Apr 16 13:27:38 CST 2016
 */
package cc.devfun.struct.test.struct;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;

/**
 * struct EslConfig
 */
public class EslConfig extends Struct {
    private byte[] eslId;

    private byte netId;

    public EslConfig() {
        this.eslId = new byte[4];
        java.util.Arrays.fill(this.eslId, (byte) 0);

        this.netId = (byte) 0;

    }
    public byte[] getEslId() {
        return this.eslId;
    }

    public byte getNetId() {
        return this.netId;
    }

    public void setNetId(byte netId) {
        this.netId = netId;
    }


    public int calcSize() {
        int __size = 0;

        __size += 1 * 4;

        __size += 1 * 1;

        return __size;
    }

    public void encode(DataOutput dos) throws IOException {
        for (int i = 0; i < 4; ++i) {
            write(dos, this.eslId[i], byte.class);
        }

        write(dos, this.netId, byte.class);

    }

    public Struct decode(DataInput dis) throws IOException {
        for (int i = 0; i < 4; ++i) {
            this.eslId[i] = read(dis, byte.class);
        }

        this.netId = read(dis, byte.class);

        return this;
    }
}
